//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMDesignTwoDetial
    {
        public string Id { get; set; }
        public string BOMDesignTwoId { get; set; }
        public int MaterialType { get; set; }
        public string MaterialId { get; set; }
        public string Specification { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public string FileIndex { get; set; }
        public int SAPIndex { get; set; }
        public string MaterialName { get; set; }
        public string MaterialCode { get; set; }
        public string ManufactureCode { get; set; }
        public string UnitName { get; set; }
        public string RawMaterial { get; set; }
        public string RawMaterialCode { get; set; }
        public decimal Weight { get; set; }
    
        public virtual BOMDesignTwo BOMDesignTwo { get; set; }
    }
}
