//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateEducation
    {
        public string Id { get; set; }
        public string CandidateId { get; set; }
        public string Name { get; set; }
        public string Major { get; set; }
        public string QualificationId { get; set; }
        public string Type { get; set; }
        public string ClassificationId { get; set; }
        public string Time { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
