//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSkill
    {
        public string Id { get; set; }
        public string SkillId { get; set; }
        public string ClassRoomId { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
