//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataDistributionFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataDistributionFile()
        {
            this.DataDistributionFileLinks = new HashSet<DataDistributionFileLink>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string FolderContain { get; set; }
        public string FolderPath { get; set; }
        public string FileName { get; set; }
        public int GetType { get; set; }
        public string FilterThongSo { get; set; }
        public bool FilterMaVatLieu { get; set; }
        public string FilterDonVi { get; set; }
        public string FilterManufacturer { get; set; }
        public string FilterRawMaterial { get; set; }
        public string FilterRawMaterialCode { get; set; }
        public string FilterMaterialCodeStart { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public bool MAT { get; set; }
        public bool TEM { get; set; }
        public string Extension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataDistributionFileLink> DataDistributionFileLinks { get; set; }
    }
}
