//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignStructureFile
    {
        public string Id { get; set; }
        public string DesignStructureId { get; set; }
        public string Name { get; set; }
        public bool Exist { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public bool IsTemplate { get; set; }
        public bool IsInsertData { get; set; }
    }
}
