//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPromulgate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentPromulgate()
        {
            this.DocumentPromulgateFiles = new HashSet<DocumentPromulgateFile>();
        }
    
        public string Id { get; set; }
        public string DocumentId { get; set; }
        public string Reason { get; set; }
        public string Content { get; set; }
        public System.DateTime PromulgateDate { get; set; }
        public string Version { get; set; }
        public int Index { get; set; }
    
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentPromulgateFile> DocumentPromulgateFiles { get; set; }
    }
}
