//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContract
    {
        public string Id { get; set; }
        public string EmployeeId { get; set; }
        public string LaborContractId { get; set; }
        public Nullable<System.DateTime> ContractFrom { get; set; }
        public Nullable<System.DateTime> ContractTo { get; set; }
        public string FileName { get; set; }
        public string FileSize { get; set; }
        public string FilePath { get; set; }
    }
}
