//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHistoryAppoint
    {
        public string Id { get; set; }
        public string EmployeeId { get; set; }
        public System.DateTime DateAppoint { get; set; }
        public string PositionId { get; set; }
        public string DepartmentId { get; set; }
        public string FileName { get; set; }
        public string FileSize { get; set; }
        public string FilePath { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
