//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorChangedPlan
    {
        public string Id { get; set; }
        public string ProjectId { get; set; }
        public string ErrorId { get; set; }
        public string ErrorFixId { get; set; }
        public Nullable<System.DateTime> OldStartDate { get; set; }
        public Nullable<System.DateTime> OldFinishDate { get; set; }
        public Nullable<System.DateTime> NewStartDate { get; set; }
        public Nullable<System.DateTime> NewFinishDate { get; set; }
        public string Reason { get; set; }
        public string ChangeBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
