//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertWorkplace
    {
        public string Id { get; set; }
        public string WorkplaceId { get; set; }
        public string ExpertId { get; set; }
        public string Status { get; set; }
    
        public virtual Expert Expert { get; set; }
        public virtual Workplace Workplace { get; set; }
    }
}
