//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalEmployee
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string ImagePath { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string BankAccount { get; set; }
        public string TaxCode { get; set; }
        public string IdentifyNum { get; set; }
        public System.DateTime IdentifyDate { get; set; }
        public string IdentifyAddress { get; set; }
        public string CurrentAddress { get; set; }
        public string CurrentAddressProvinceId { get; set; }
        public string CurrentAddressDistrictId { get; set; }
        public string CurrentAddressWardId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
    }
}
