//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowStageOutputResult
    {
        public string Id { get; set; }
        public string FlowStageId { get; set; }
        public string OutputResultId { get; set; }
    
        public virtual FlowStage FlowStage { get; set; }
        public virtual OutputRessult OutputRessult { get; set; }
    }
}
