//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderDefinition
    {
        public string FolderDefinitionId { get; set; }
        public int TypeDefinitionId { get; set; }
        public string FolderDefinitionManageId { get; set; }
        public string FolderDefinitionFirst { get; set; }
        public int FolderDefinitionBetween { get; set; }
        public string FolderDefinitionLast { get; set; }
        public int StatusCheckFile { get; set; }
        public int FolderType { get; set; }
        public int FolderDefinitionBetweenIndex { get; set; }
        public int StatusCheckFolder { get; set; }
        public string ExtensionFile { get; set; }
        public int ObjectType { get; set; }
        public string DepartmentId { get; set; }
    }
}
