//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermission
    {
        public string Id { get; set; }
        public string GroupUserId { get; set; }
        public string PermissionId { get; set; }
    
        public virtual GroupUser GroupUser { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
