//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.ModuleDesignDocuments = new HashSet<ModuleDesignDocument>();
            this.ModuleMaterials = new HashSet<ModuleMaterial>();
            this.ModuleProductStandards = new HashSet<ModuleProductStandard>();
            this.SketchAttaches = new HashSet<SketchAttach>();
            this.SketchMaterialElectronics = new HashSet<SketchMaterialElectronic>();
            this.SketchMaterialMechanicals = new HashSet<SketchMaterialMechanical>();
        }
    
        public string Id { get; set; }
        public string ModuleGroupId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public int Status { get; set; }
        public int State { get; set; }
        public string Specification { get; set; }
        public bool FileElectric { get; set; }
        public bool ElectricExist { get; set; }
        public bool FileElectronic { get; set; }
        public bool ElectronicExist { get; set; }
        public bool FileMechanics { get; set; }
        public bool MechanicsExist { get; set; }
        public bool IsSoftware { get; set; }
        public bool SoftwareExist { get; set; }
        public decimal Pricing { get; set; }
        public bool IsHMI { get; set; }
        public bool HMIExist { get; set; }
        public bool IsPLC { get; set; }
        public bool PLCExist { get; set; }
        public int CurrentVersion { get; set; }
        public string ThumbnailPath { get; set; }
        public bool IsFilm { get; set; }
        public bool IsDMTV { get; set; }
        public bool FilmExist { get; set; }
        public string Description { get; set; }
        public string EditContent { get; set; }
        public int Leadtime { get; set; }
        public string DepartmentId { get; set; }
        public bool IsManual { get; set; }
        public bool ManualExist { get; set; }
        public bool IsSendSale { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleDesignDocument> ModuleDesignDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleMaterial> ModuleMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleProductStandard> ModuleProductStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SketchAttach> SketchAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SketchMaterialElectronic> SketchMaterialElectronics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SketchMaterialMechanical> SketchMaterialMechanicals { get; set; }
    }
}
