//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanAssignment
    {
        public string Id { get; set; }
        public string PlanId { get; set; }
        public string UserId { get; set; }
        public bool IsMain { get; set; }
        public string EmployeeId { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual User User { get; set; }
    }
}
