//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Plans = new HashSet<Plan>();
            this.ProjectAttaches = new HashSet<ProjectAttach>();
            this.ProjectSolutions = new HashSet<ProjectSolution>();
            this.ProjectTransferAttaches = new HashSet<ProjectTransferAttach>();
        }
    
        public string Id { get; set; }
        public string CustomerId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Parameter { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> KickOffDate { get; set; }
        public string SBUId { get; set; }
        public string DepartmentId { get; set; }
        public decimal Price { get; set; }
        public decimal DesignPrice { get; set; }
        public string WarehouseCode { get; set; }
        public string CustomerFinalId { get; set; }
        public decimal SaleNoVAT { get; set; }
        public decimal FCMPrice { get; set; }
        public int DocumentStatus { get; set; }
        public int Type { get; set; }
        public string ManageId { get; set; }
        public int Priority { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public string Status { get; set; }
        public string Progress { get; set; }
        public bool IsBadDebt { get; set; }
        public Nullable<System.DateTime> BadDebtDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAttach> ProjectAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSolution> ProjectSolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTransferAttach> ProjectTransferAttaches { get; set; }
    }
}
