//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectGeneralDesign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectGeneralDesign()
        {
            this.ProjectGeneralDesignModules = new HashSet<ProjectGeneralDesignModule>();
            this.ProjectGeneralDesignMaterials = new HashSet<ProjectGeneralDesignMaterial>();
        }
    
        public string Id { get; set; }
        public string Index { get; set; }
        public string DepartmentRequestId { get; set; }
        public string DepartmentCreateId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string ProjectProductId { get; set; }
        public string ProjectId { get; set; }
        public int CreateIndex { get; set; }
        public string DesignBy { get; set; }
        public int ApproveStatus { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectGeneralDesignModule> ProjectGeneralDesignModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectGeneralDesignMaterial> ProjectGeneralDesignMaterials { get; set; }
    }
}
