//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleProductExport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleProductExport()
        {
            this.SaleProductExportDetails = new HashSet<SaleProductExportDetail>();
        }
    
        public string Id { get; set; }
        public string Code { get; set; }
        public string CustomerId { get; set; }
        public int Status { get; set; }
        public int Index { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public int ProductQuantity { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public decimal PaymentPercent { get; set; }
        public decimal PaymentAmount { get; set; }
        public int PayStatus { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProductExportDetail> SaleProductExportDetails { get; set; }
    }
}
