//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleProduct()
        {
            this.SaleGroupProducts = new HashSet<SaleGroupProduct>();
            this.SaleProductDocuments = new HashSet<SaleProductDocument>();
            this.SaleProductMedias = new HashSet<SaleProductMedia>();
            this.SaleProductApplications = new HashSet<SaleProductApplication>();
            this.SaleProductJobs = new HashSet<SaleProductJob>();
            this.SaleProductAccessories = new HashSet<SaleProductAccessory>();
        }
    
        public string Id { get; set; }
        public string SaleProductTypeId { get; set; }
        public string EName { get; set; }
        public string VName { get; set; }
        public string Model { get; set; }
        public string GroupCode { get; set; }
        public string ChildGroupCode { get; set; }
        public string ManufactureId { get; set; }
        public string CountryName { get; set; }
        public string Specifications { get; set; }
        public string CustomerSpecifications { get; set; }
        public Nullable<System.DateTime> SpecificationDate { get; set; }
        public decimal VAT { get; set; }
        public decimal MaterialPrice { get; set; }
        public decimal EXWTPAPrice { get; set; }
        public Nullable<System.DateTime> EXWTPADate { get; set; }
        public decimal PublicPrice { get; set; }
        public Nullable<System.DateTime> ExpireDateFrom { get; set; }
        public Nullable<System.DateTime> ExpireDateTo { get; set; }
        public string DeliveryTime { get; set; }
        public decimal Inventory { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public decimal ExportQuantity { get; set; }
        public decimal AvailableQuantity { get; set; }
        public int Type { get; set; }
        public bool Status { get; set; }
        public bool IsSync { get; set; }
        public bool ExistSolution { get; set; }
        public bool ExistCatalog { get; set; }
        public bool ExistTrainingTechnique { get; set; }
        public bool ExistTrainingSale { get; set; }
        public bool ExistUserManual { get; set; }
        public bool ExistFixBug { get; set; }
        public string SourceId { get; set; }
        public string AvatarPath { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsChoose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleGroupProduct> SaleGroupProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProductDocument> SaleProductDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProductMedia> SaleProductMedias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProductApplication> SaleProductApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProductJob> SaleProductJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProductAccessory> SaleProductAccessories { get; set; }
    }
}
