//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTargetment
    {
        public string Id { get; set; }
        public string EmployeeId { get; set; }
        public string DepartmentId { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public int Year { get; set; }
        public Nullable<long> SaleTarget { get; set; }
        public string DomainId { get; set; }
        public string IndustryId { get; set; }
        public string ApplicationTypeId { get; set; }
        public Nullable<System.DateTime> PlanContractDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
