//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleProductExportDetail
    {
        public string Id { get; set; }
        public string SaleProductId { get; set; }
        public string SaleProductExportId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Inventory { get; set; }
        public decimal AvailableQuantity { get; set; }
    
        public virtual SaleProductExport SaleProductExport { get; set; }
    }
}
