//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimilarMaterialConfig
    {
        public string Id { get; set; }
        public string SimilarMaterialId { get; set; }
        public string MaterialId { get; set; }
        public string Parameter { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual SimilarMaterial SimilarMaterial { get; set; }
    }
}
