//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecializeInPracticeGroup
    {
        public string Id { get; set; }
        public string SpecializeId { get; set; }
        public string PracticeGroupId { get; set; }
    
        public virtual PracticeGroup PracticeGroup { get; set; }
        public virtual Specialize Specialize { get; set; }
    }
}
