//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.JobSubjects = new HashSet<JobSubject>();
            this.SubjectSkills = new HashSet<SubjectSkill>();
            this.SubjectsAttaches = new HashSet<SubjectsAttach>();
            this.SubjectsClassRooms = new HashSet<SubjectsClassRoom>();
        }
    
        public string Id { get; set; }
        public string DegreeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalLearningTime { get; set; }
        public Nullable<int> LearningTheoryTime { get; set; }
        public Nullable<int> LearningPracticeTime { get; set; }
        public string Description { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Documents { get; set; }
    
        public virtual Degree Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSubject> JobSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectSkill> SubjectSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectsAttach> SubjectsAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectsClassRoom> SubjectsClassRooms { get; set; }
    }
}
