//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyTool
    {
        public string Id { get; set; }
        public string SurveyId { get; set; }
        public string MaterialId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int Quantity { get; set; }
        public string Note { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
