//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskInputRessults = new HashSet<TaskInputRessult>();
            this.TaskMaterils = new HashSet<TaskMateril>();
            this.TaskModuleGroups = new HashSet<TaskModuleGroup>();
            this.TaskModuleGroups1 = new HashSet<TaskModuleGroup>();
            this.TaskOutputRessults = new HashSet<TaskOutputRessult>();
            this.TaskSkills = new HashSet<TaskSkill>();
            this.TaskTimeStandards = new HashSet<TaskTimeStandard>();
            this.TaskWorkTypes = new HashSet<TaskWorkType>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsDesignModule { get; set; }
        public Nullable<decimal> TimeStandard { get; set; }
        public string DegreeId { get; set; }
        public string Specialization { get; set; }
        public string SpecializeId { get; set; }
        public string WorkTypeRId { get; set; }
        public string WorkTypeAId { get; set; }
        public string WorkTypeSId { get; set; }
        public string WorkTypeCId { get; set; }
        public string WorkTypeIId { get; set; }
        public string SBUId { get; set; }
        public string DepartmentId { get; set; }
        public string FlowStageId { get; set; }
        public Nullable<decimal> PercentValue { get; set; }
        public bool IsProjectWork { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskInputRessult> TaskInputRessults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskMateril> TaskMaterils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskModuleGroup> TaskModuleGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskModuleGroup> TaskModuleGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskOutputRessult> TaskOutputRessults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskSkill> TaskSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTimeStandard> TaskTimeStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskWorkType> TaskWorkTypes { get; set; }
    }
}
