//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCriteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestCriteria()
        {
            this.ModuleTestCriterias = new HashSet<ModuleTestCriteria>();
            this.ProjectProductTestCriterias = new HashSet<ProjectProductTestCriteria>();
        }
    
        public string Id { get; set; }
        public string TestCriteriaGroupId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TechnicalRequirements { get; set; }
        public string Note { get; set; }
        public int DataType { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleTestCriteria> ModuleTestCriterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectProductTestCriteria> ProjectProductTestCriterias { get; set; }
        public virtual TestCriteriaGroup TestCriteriaGroup { get; set; }
    }
}
