//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTS.Common.Resource.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi phát sinh trong quy trình xử lý!.
        /// </summary>
        public static string ERR0001 {
            get {
                return ResourceManager.GetString("ERR0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại!.
        /// </summary>
        public static string MSG0001 {
            get {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên {0} đã tồn tại. Vui lòng nhập tên {0} khác!.
        /// </summary>
        public static string MSG0002 {
            get {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã {0} đã tồn tại. Vui lòng nhập mã {0} khác!.
        /// </summary>
        public static string MSG0003 {
            get {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đang được sử dụng. Không được phép xóa.
        /// </summary>
        public static string MSG0004 {
            get {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} đã tồn tại.Nhập Version khác!.
        /// </summary>
        public static string MSG0005 {
            get {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên đã có trong danh sách. Bạn vui lòng chọn nhân viên khác .
        /// </summary>
        public static string MSG0006 {
            get {
                return ResourceManager.GetString("MSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} đã tồn tại. Vui lòng nhập email{0} khác!.
        /// </summary>
        public static string MSG0007 {
            get {
                return ResourceManager.GetString("MSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian chỉ nhập số.
        /// </summary>
        public static string MSG0008 {
            get {
                return ResourceManager.GetString("MSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version chỉ được nhập số.
        /// </summary>
        public static string MSG0009 {
            get {
                return ResourceManager.GetString("MSG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version phải lớn hơn 0.
        /// </summary>
        public static string MSG0010 {
            get {
                return ResourceManager.GetString("MSG0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version mới phải lớn hơn version cũ.
        /// </summary>
        public static string MSG0011 {
            get {
                return ResourceManager.GetString("MSG0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc phải lớn hơn thời gian bắt đầu.
        /// </summary>
        public static string MSG0012 {
            get {
                return ResourceManager.GetString("MSG0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày làm việc phải nhỏ hơn ngày nghỉ.
        /// </summary>
        public static string MSG0013 {
            get {
                return ResourceManager.GetString("MSG0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại này đã tồn tại.
        /// </summary>
        public static string MSG0014 {
            get {
                return ResourceManager.GetString("MSG0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu {0}.
        /// </summary>
        public static string MSG0015 {
            get {
                return ResourceManager.GetString("MSG0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm vật tư tương tự đã có vật tư không được phép xóa.
        /// </summary>
        public static string MSG0016 {
            get {
                return ResourceManager.GetString("MSG0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư đã có trong nhóm khác.
        /// </summary>
        public static string MSG0017 {
            get {
                return ResourceManager.GetString("MSG0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đang làm việc. Không thể xóa.
        /// </summary>
        public static string MSG0018 {
            get {
                return ResourceManager.GetString("MSG0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chưa được cấu hình. Vui lòng cấu hình!.
        /// </summary>
        public static string MSG0019 {
            get {
                return ResourceManager.GetString("MSG0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại công việc của nhân viên đã tồn tại!.
        /// </summary>
        public static string MSG0020 {
            get {
                return ResourceManager.GetString("MSG0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên theo hợp đồng đã tồn tại. Nhập tên theo hợp đồng khác!.
        /// </summary>
        public static string MSG0023 {
            get {
                return ResourceManager.GetString("MSG0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã theo hợp đồng đã tồn tại. Nhập mã theo hợp đồng khác!.
        /// </summary>
        public static string MSG0024 {
            get {
                return ResourceManager.GetString("MSG0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã {0} không bắt đầu bằng nhóm {0}. Vui lòng kiểm tra lại!.
        /// </summary>
        public static string MSG0025 {
            get {
                return ResourceManager.GetString("MSG0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục upload chưa được cấu hình.
        /// </summary>
        public static string MSG0026 {
            get {
                return ResourceManager.GetString("MSG0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được sửa {0} thành con của chính nó hoặc con của nó.
        /// </summary>
        public static string MSG0027 {
            get {
                return ResourceManager.GetString("MSG0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã {0} phải bắt đầu bằng mã nhóm {0}.
        /// </summary>
        public static string MSG0028 {
            get {
                return ResourceManager.GetString("MSG0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thuộc phòng ban của bạn. Không được phép chỉnh sửa.
        /// </summary>
        public static string MSG0029 {
            get {
                return ResourceManager.GetString("MSG0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thao tac {0} này..
        /// </summary>
        public static string MSG0030 {
            get {
                return ResourceManager.GetString("MSG0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thuộc SBU của bạn. Không được phép thực hiện thao tác này.
        /// </summary>
        public static string MSG0031 {
            get {
                return ResourceManager.GetString("MSG0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không phải do bạn tạo ra. Không được phép chỉnh sửa.
        /// </summary>
        public static string MSG0032 {
            get {
                return ResourceManager.GetString("MSG0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thuộc phòng ban. Không được phép thêm mới.
        /// </summary>
        public static string MSG0033 {
            get {
                return ResourceManager.GetString("MSG0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thuộc phòng ban. Không được phép chỉnh sửa.
        /// </summary>
        public static string MSG0034 {
            get {
                return ResourceManager.GetString("MSG0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thuộc phòng ban. Không được phép xóa.
        /// </summary>
        public static string MSG0035 {
            get {
                return ResourceManager.GetString("MSG0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Không thuộc SBU của bạn. Không được phép xóa.
        /// </summary>
        public static string MSG0036 {
            get {
                return ResourceManager.GetString("MSG0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không phải do bạn tạo ra. Không được phép xóa.
        /// </summary>
        public static string MSG0037 {
            get {
                return ResourceManager.GetString("MSG0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dữ liệu phải là file Exel.
        /// </summary>
        public static string MSG0038 {
            get {
                return ResourceManager.GetString("MSG0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không có dữ liệu!.
        /// </summary>
        public static string MSG0039 {
            get {
                return ResourceManager.GetString("MSG0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thất bại.
        /// </summary>
        public static string MSG0040 {
            get {
                return ResourceManager.GetString("MSG0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng!.
        /// </summary>
        public static string MSG0052 {
            get {
                return ResourceManager.GetString("MSG0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới {0} Tên/Mã: {1}.
        /// </summary>
        public static string MSG0053 {
            get {
                return ResourceManager.GetString("MSG0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0} Tên/Mã: {1}.
        /// </summary>
        public static string MSG0054 {
            get {
                return ResourceManager.GetString("MSG0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0} của {1} Tên/Mã: {2}.
        /// </summary>
        public static string MSG0055 {
            get {
                return ResourceManager.GetString("MSG0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa {0} Tên/Mã: {1}.
        /// </summary>
        public static string MSG0056 {
            get {
                return ResourceManager.GetString("MSG0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa {0} Tên/mã {1} của {2} Tên/Mã: {3}.
        /// </summary>
        public static string MSG0057 {
            get {
                return ResourceManager.GetString("MSG0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} của {1} Tên/Mã: {2}.
        /// </summary>
        public static string MSG0058 {
            get {
                return ResourceManager.GetString("MSG0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0}.
        /// </summary>
        public static string MSG0059 {
            get {
                return ResourceManager.GetString("MSG0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo {0}.
        /// </summary>
        public static string MSG0060 {
            get {
                return ResourceManager.GetString("MSG0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yều xác nhận {0}.
        /// </summary>
        public static string MSG0061 {
            get {
                return ResourceManager.GetString("MSG0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy yều xác nhận {0}.
        /// </summary>
        public static string MSG0062 {
            get {
                return ResourceManager.GetString("MSG0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận {0}.
        /// </summary>
        public static string MSG0063 {
            get {
                return ResourceManager.GetString("MSG0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy xác nhận {0}.
        /// </summary>
        public static string MSG0064 {
            get {
                return ResourceManager.GetString("MSG0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xử lý {0}.
        /// </summary>
        public static string MSG0065 {
            get {
                return ResourceManager.GetString("MSG0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy đã xử lý {0}.
        /// </summary>
        public static string MSG0066 {
            get {
                return ResourceManager.GetString("MSG0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC đạt {0}.
        /// </summary>
        public static string MSG0067 {
            get {
                return ResourceManager.GetString("MSG0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC không đạt {0}.
        /// </summary>
        public static string MSG0068 {
            get {
                return ResourceManager.GetString("MSG0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy kết quả QC {0}.
        /// </summary>
        public static string MSG0069 {
            get {
                return ResourceManager.GetString("MSG0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng {0}.
        /// </summary>
        public static string MSG0070 {
            get {
                return ResourceManager.GetString("MSG0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy đóng {0}.
        /// </summary>
        public static string MSG0071 {
            get {
                return ResourceManager.GetString("MSG0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có module thiếu giá không được xuất THTK..
        /// </summary>
        public static string MSG0072 {
            get {
                return ResourceManager.GetString("MSG0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có mã: {1} không tồn tại trên hệ thống!.
        /// </summary>
        public static string MSG0073 {
            get {
                return ResourceManager.GetString("MSG0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn nhập nhật ký công việc là: {0}. Bạn đã nhập nhật ký quá hạn!.
        /// </summary>
        public static string MSG0074 {
            get {
                return ResourceManager.GetString("MSG0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên {0} không được để trống.
        /// </summary>
        public static string MSG0075 {
            get {
                return ResourceManager.GetString("MSG0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã {0} không được để trống.
        /// </summary>
        public static string MSG0076 {
            get {
                return ResourceManager.GetString("MSG0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã hoàn thành không được phép xóa!.
        /// </summary>
        public static string MSG0077 {
            get {
                return ResourceManager.GetString("MSG0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư đã được tạo hồ sơ không được phép xóa.
        /// </summary>
        public static string MSG0078 {
            get {
                return ResourceManager.GetString("MSG0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư: {}, đã được tạo hồ sơ không được tạo hồ sơ nữa.
        /// </summary>
        public static string MSG0079 {
            get {
                return ResourceManager.GetString("MSG0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đang được sử dụng ở {1}. Không được phép xóa.
        /// </summary>
        public static string MSG0081 {
            get {
                return ResourceManager.GetString("MSG0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Không thuộc SBU của bạn. Không được phép thêm mới..
        /// </summary>
        public static string MSG0082 {
            get {
                return ResourceManager.GetString("MSG0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã ban hành..
        /// </summary>
        public static string MSG0083 {
            get {
                return ResourceManager.GetString("MSG0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} đã tồn tại. Vui lòng nhập {1} {0} khác!.
        /// </summary>
        public static string MSG0084 {
            get {
                return ResourceManager.GetString("MSG0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có kế hoạch {0}.
        /// </summary>
        public static string MSG0085 {
            get {
                return ResourceManager.GetString("MSG0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy Đã có kế hoạch {0}.
        /// </summary>
        public static string MSG0086 {
            get {
                return ResourceManager.GetString("MSG0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vấn đề đã có kế hoạch không được phép hủy.
        /// </summary>
        public static string MSG0087 {
            get {
                return ResourceManager.GetString("MSG0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã LogTime. Không được phép xóa!.
        /// </summary>
        public static string MSG0088 {
            get {
                return ResourceManager.GetString("MSG0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chỉ nhận giá trị nguyên dương!.
        /// </summary>
        public static string MSG0089 {
            get {
                return ResourceManager.GetString("MSG0089", resourceCulture);
            }
        }
    }
}
