//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTrainingSkill
    {
        public string Id { get; set; }
        public string CourseTrainingId { get; set; }
        public string WorkSkillId { get; set; }
        public int Mark { get; set; }
        public int OldMark { get; set; }
        public string CourseSkillId { get; set; }
        public string EmployeeId { get; set; }
    
        public virtual CourseTraining CourseTraining { get; set; }
        public virtual WorkSkill WorkSkill { get; set; }
    }
}
