//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerRequirement()
        {
            this.CustomerRequirementAttaches = new HashSet<CustomerRequirementAttach>();
            this.CustomerRequirementContents = new HashSet<CustomerRequirementContent>();
            this.ProtectSolutions = new HashSet<ProtectSolution>();
        }
    
        public string Id { get; set; }
        public string CustomerId { get; set; }
        public string CustomerContactId { get; set; }
        public int RequestType { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string MeetingCode { get; set; }
        public decimal Budget { get; set; }
        public string Petitioner { get; set; }
        public string DepartmentRequest { get; set; }
        public string Reciever { get; set; }
        public string DepartmentReceive { get; set; }
        public Nullable<System.DateTime> RealFinishDate { get; set; }
        public int RequestSource { get; set; }
        public string Note { get; set; }
        public int Status { get; set; }
        public int Version { get; set; }
        public int Index { get; set; }
        public int Step { get; set; }
        public string Competitor { get; set; }
        public string CustomerSupplier { get; set; }
        public string ProjectPhaseId { get; set; }
        public int PriorityLevel { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string Content3 { get; set; }
        public Nullable<bool> Conclude1 { get; set; }
        public Nullable<bool> Conclude2 { get; set; }
        public Nullable<bool> Conclude3 { get; set; }
        public string Person1 { get; set; }
        public string Person2 { get; set; }
        public string Person3 { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.DateTime> PlanFinishDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> CustomerRequirementState { get; set; }
        public Nullable<int> CustomerRequirementAnalysisState { get; set; }
        public Nullable<int> SurveyState { get; set; }
        public Nullable<int> SolutionAnalysisState { get; set; }
        public Nullable<int> EstimateState { get; set; }
        public Nullable<int> DoSolutionAnalysisState { get; set; }
        public string DomainId { get; set; }
    
        public virtual CustomerContact CustomerContact { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRequirementAttach> CustomerRequirementAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRequirementContent> CustomerRequirementContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtectSolution> ProtectSolutions { get; set; }
    }
}
