//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentFiles = new HashSet<DocumentFile>();
            this.DocumentMeetings = new HashSet<DocumentMeeting>();
            this.DocumentObjects = new HashSet<DocumentObject>();
            this.DocumentPromulgates = new HashSet<DocumentPromulgate>();
            this.DocumentProblems = new HashSet<DocumentProblem>();
            this.DocumentReferences = new HashSet<DocumentReference>();
        }
    
        public string Id { get; set; }
        public string DocumentGroupId { get; set; }
        public string DocumentTypeId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Version { get; set; }
        public int CompilationType { get; set; }
        public string CompilationEmployeeId { get; set; }
        public string CompilationSuppliserId { get; set; }
        public Nullable<System.DateTime> PromulgateDate { get; set; }
        public Nullable<System.DateTime> PromulgateLastDate { get; set; }
        public string DepartmentId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> ReviewDateFrom { get; set; }
        public Nullable<System.DateTime> ReviewDateTo { get; set; }
        public decimal Price { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string ApproveWorkTypeId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Status { get; set; }
    
        public virtual DocumentGroup DocumentGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentFile> DocumentFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentMeeting> DocumentMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentObject> DocumentObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentPromulgate> DocumentPromulgates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentProblem> DocumentProblems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentReference> DocumentReferences { get; set; }
    }
}
