//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkillDetail
    {
        public string Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<decimal> LevelRate { get; set; }
        public System.DateTime RateDate { get; set; }
        public Nullable<decimal> LevelRate1 { get; set; }
        public System.DateTime RateDate1 { get; set; }
        public Nullable<decimal> LevelRate2 { get; set; }
        public System.DateTime RateDate2 { get; set; }
        public string Note { get; set; }
        public string SkillId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
