//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDegree
    {
        public string Id { get; set; }
        public string QualificationId { get; set; }
        public string EmployeeId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Year { get; set; }
        public string National { get; set; }
        public string School { get; set; }
        public string Type { get; set; }
        public string Rank { get; set; }
        public string Description { get; set; }
        public string ClassificationId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
