//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorFix
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ErrorFix()
        {
            this.ErrorFixAttachs = new HashSet<ErrorFixAttach>();
        }
    
        public string Id { get; set; }
        public string ErrorId { get; set; }
        public string DepartmentId { get; set; }
        public string EmployeeFixId { get; set; }
        public string Solution { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public int Status { get; set; }
        public string SupportId { get; set; }
        public string ApproveId { get; set; }
        public string AdviseId { get; set; }
        public string NotifyId { get; set; }
        public int Deadline { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public int Done { get; set; }
        public Nullable<decimal> EstimateTime { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorFixAttach> ErrorFixAttachs { get; set; }
        public virtual Error Error { get; set; }
    }
}
