//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewQuestion
    {
        public string Id { get; set; }
        public string InterviewId { get; set; }
        public string Answer { get; set; }
        public int Score { get; set; }
        public string QuestionAnswer { get; set; }
        public string QuestionContent { get; set; }
        public int QuestionScore { get; set; }
        public int QuestionType { get; set; }
        public int Status { get; set; }
        public string QuestionCode { get; set; }
    
        public virtual Interview Interview { get; set; }
    }
}
