//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.ConverUnits = new HashSet<ConverUnit>();
            this.MaterialBuyHistories = new HashSet<MaterialBuyHistory>();
            this.MaterialImages = new HashSet<MaterialImage>();
            this.MaterialModuleGroups = new HashSet<MaterialModuleGroup>();
            this.SketchMaterialMechanicals = new HashSet<SketchMaterialMechanical>();
            this.ModuleMaterials = new HashSet<ModuleMaterial>();
            this.SimilarMaterialConfigs = new HashSet<SimilarMaterialConfig>();
            this.SketchMaterialElectronics = new HashSet<SketchMaterialElectronic>();
            this.SurveyTools = new HashSet<SurveyTool>();
        }
    
        public string Id { get; set; }
        public string MaterialGroupId { get; set; }
        public string MaterialGroupTPAId { get; set; }
        public string UnitId { get; set; }
        public string ManufactureId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public decimal Pricing { get; set; }
        public decimal PriceHistory { get; set; }
        public int DeliveryDays { get; set; }
        public string ImagePath { get; set; }
        public string ThumbnailPath { get; set; }
        public Nullable<System.DateTime> LastBuyDate { get; set; }
        public Nullable<System.DateTime> InputPriceDate { get; set; }
        public Nullable<bool> IsUsuallyUse { get; set; }
        public string MaterialType { get; set; }
        public string MechanicalType { get; set; }
        public string RawMaterial { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Is3D { get; set; }
        public bool Is3DExist { get; set; }
        public Nullable<bool> IsDataSheet { get; set; }
        public bool IsDatasheetExist { get; set; }
        public string Weight { get; set; }
        public string RawMaterialId { get; set; }
        public string ModuleGroupId { get; set; }
        public bool IsSetup { get; set; }
        public string Specification { get; set; }
        public bool IsSendSale { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsRedundant { get; set; }
        public int RedundantAmount { get; set; }
        public string RedundantDescription { get; set; }
        public string RedundantDeliveryNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConverUnit> ConverUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialBuyHistory> MaterialBuyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialImage> MaterialImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialModuleGroup> MaterialModuleGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SketchMaterialMechanical> SketchMaterialMechanicals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleMaterial> ModuleMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimilarMaterialConfig> SimilarMaterialConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SketchMaterialElectronic> SketchMaterialElectronics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyTool> SurveyTools { get; set; }
    }
}
