//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialImportBOMDraft
    {
        public string Id { get; set; }
        public string ProjectId { get; set; }
        public string ModuleId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Specification { get; set; }
        public string RawMaterialCode { get; set; }
        public string RawMaterial { get; set; }
        public string UnitName { get; set; }
        public decimal Weight { get; set; }
        public decimal Quantity { get; set; }
        public decimal Pricing { get; set; }
        public string Note { get; set; }
        public decimal Amount { get; set; }
        public string ManufactureCode { get; set; }
        public string Index { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> UpdateStatus { get; set; }
    }
}
