//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingContent()
        {
            this.MeetingContentAttaches = new HashSet<MeetingContentAttach>();
        }
    
        public string Id { get; set; }
        public string MeetingId { get; set; }
        public string Request { get; set; }
        public string Solution { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Code { get; set; }
        public int Index { get; set; }
        public string RequestBy { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingContentAttach> MeetingContentAttaches { get; set; }
    }
}
