//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingCustomerContact
    {
        public string Id { get; set; }
        public string CustomerContactId { get; set; }
        public string MeetingId { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual CustomerContact CustomerContact { get; set; }
        public virtual Meeting Meeting { get; set; }
    }
}
