//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.MeetingAttaches = new HashSet<MeetingAttach>();
            this.MeetingContents = new HashSet<MeetingContent>();
            this.MeetingContentAttaches = new HashSet<MeetingContentAttach>();
            this.MeetingCustomerContacts = new HashSet<MeetingCustomerContact>();
            this.MeetingUsers = new HashSet<MeetingUser>();
        }
    
        public string Id { get; set; }
        public int Type { get; set; }
        public string MeetingTypeId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CodeChar { get; set; }
        public int Index { get; set; }
        public string CustomerId { get; set; }
        public string CustomerContactId { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string RealStartTime { get; set; }
        public string RealEndTime { get; set; }
        public int Time { get; set; }
        public int Status { get; set; }
        public int Step { get; set; }
        public string ReasonCancel { get; set; }
        public string Description { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Request { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    
        public virtual MeetingType MeetingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingAttach> MeetingAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingContent> MeetingContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingContentAttach> MeetingContentAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingCustomerContact> MeetingCustomerContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingUser> MeetingUsers { get; set; }
    }
}
