//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleMaterial()
        {
            this.ModuleMaterialAttaches = new HashSet<ModuleMaterialAttach>();
            this.ProductModuleMaterials = new HashSet<ProductModuleMaterial>();
        }
    
        public string Id { get; set; }
        public string ModuleId { get; set; }
        public string MaterialId { get; set; }
        public string Index { get; set; }
        public string MaterialName { get; set; }
        public string Specification { get; set; }
        public string MaterialCode { get; set; }
        public string RawMaterialCode { get; set; }
        public string UnitName { get; set; }
        public decimal Quantity { get; set; }
        public string RawMaterial { get; set; }
        public decimal Weight { get; set; }
        public string ManufacturerCode { get; set; }
        public string Note { get; set; }
        public decimal Price { get; set; }
        public decimal Amount { get; set; }
        public string ManufacturerId { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleMaterialAttach> ModuleMaterialAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductModuleMaterial> ProductModuleMaterials { get; set; }
    }
}
