//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string Id { get; set; }
        public string ProjectId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PlanPaymentDate { get; set; }
        public Nullable<decimal> PlanAmount { get; set; }
        public string PaymentCondition { get; set; }
        public Nullable<System.DateTime> ActualPaymentDate1 { get; set; }
        public decimal ActualAmount1 { get; set; }
        public Nullable<System.DateTime> ActualPaymentDate2 { get; set; }
        public decimal ActualAmount2 { get; set; }
        public Nullable<System.DateTime> ActualPaymentDate3 { get; set; }
        public decimal ActualAmount3 { get; set; }
        public Nullable<System.DateTime> ActualPaymentDate4 { get; set; }
        public decimal ActualAmount4 { get; set; }
        public Nullable<System.DateTime> ActualPaymentDate5 { get; set; }
        public decimal ActualAmount5 { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<System.DateTime> PaymentMilestone { get; set; }
        public int MoneyCollectionTime { get; set; }
    }
}
