//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanHistory()
        {
            this.PlanHistoryAttaches = new HashSet<PlanHistoryAttach>();
        }
    
        public string Id { get; set; }
        public string ProjectId { get; set; }
        public int Version { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public string Content { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanHistoryAttach> PlanHistoryAttaches { get; set; }
    }
}
