//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Practice()
        {
            this.PracticeMaterialConsumables = new HashSet<PracticeMaterialConsumable>();
            this.PracticeSkills = new HashSet<PracticeSkill>();
            this.PracticeExperts = new HashSet<PracticeExpert>();
            this.PracticeFiles = new HashSet<PracticeFile>();
            this.PracticeMaterials = new HashSet<PracticeMaterial>();
            this.PracticeSubMaterials = new HashSet<PracticeSubMaterial>();
        }
    
        public string Id { get; set; }
        public string PracticeGroupId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CurentVersion { get; set; }
        public string EditContent { get; set; }
        public string Note { get; set; }
        public string Content { get; set; }
        public int TrainingTime { get; set; }
        public decimal LessonPrice { get; set; }
        public decimal HardwarePrice { get; set; }
        public string UnitId { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
        public int LeadTime { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> PracticeFile { get; set; }
        public Nullable<bool> PracticeExist { get; set; }
        public Nullable<bool> SupMaterial { get; set; }
        public Nullable<bool> SupMaterialExist { get; set; }
        public Nullable<bool> MaterialConsumable { get; set; }
        public Nullable<bool> MaterialConsumableExist { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeMaterialConsumable> PracticeMaterialConsumables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeSkill> PracticeSkills { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeExpert> PracticeExperts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeFile> PracticeFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeMaterial> PracticeMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeSubMaterial> PracticeSubMaterials { get; set; }
    }
}
