//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeSubMaterial
    {
        public string Id { get; set; }
        public string MaterialId { get; set; }
        public string PracticeId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> Leadtime { get; set; }
        public int Type { get; set; }
    
        public virtual Practice Practice { get; set; }
    }
}
