//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductAccessories = new HashSet<ProductAccessory>();
            this.ProductDesignDocuments = new HashSet<ProductDesignDocument>();
            this.ProductDocuments = new HashSet<ProductDocument>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductModules = new HashSet<ProductModule>();
            this.ProductModuleMaterials = new HashSet<ProductModuleMaterial>();
            this.ProductModuleUpdates = new HashSet<ProductModuleUpdate>();
            this.ProductTestResultAttachs = new HashSet<ProductTestResultAttach>();
        }
    
        public string Id { get; set; }
        public string ProductGroupId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CurentVersion { get; set; }
        public string Content { get; set; }
        public int ProcedureTime { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string DepartmentId { get; set; }
        public bool IsManualExist { get; set; }
        public bool IsQuoteExist { get; set; }
        public bool IsPracticeExist { get; set; }
        public bool IsLayoutExist { get; set; }
        public bool IsMaterialExist { get; set; }
        public bool IsManualMaintenance { get; set; }
        public bool IsCatalog { get; set; }
        public decimal Pricing { get; set; }
        public bool IsTestResult { get; set; }
        public bool IsSendSale { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public decimal Price { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAccessory> ProductAccessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDesignDocument> ProductDesignDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDocument> ProductDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductModule> ProductModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductModuleMaterial> ProductModuleMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductModuleUpdate> ProductModuleUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTestResultAttach> ProductTestResultAttachs { get; set; }
    }
}
