//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectEmployee
    {
        public string Id { get; set; }
        public string EmployeeId { get; set; }
        public int Type { get; set; }
        public string ProjectId { get; set; }
        public string RoleId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string JobDescription { get; set; }
        public int Evaluate { get; set; }
        public bool Status { get; set; }
        public decimal Subsidy { get; set; }
        public Nullable<System.DateTime> SubsidyStartTime { get; set; }
        public Nullable<System.DateTime> SubsidyEndTime { get; set; }
        public bool HasContractPlanPermit { get; set; }
    }
}
