//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTransferProduct
    {
        public string Id { get; set; }
        public string ProjectTransferAttachId { get; set; }
        public int Quantity { get; set; }
        public string ProjectProductId { get; set; }
    
        public virtual ProjectTransferAttach ProjectTransferAttach { get; set; }
    }
}
