//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequestProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequestProduct()
        {
            this.ImportProfileProducts = new HashSet<ImportProfileProduct>();
        }
    
        public string Id { get; set; }
        public string PurchaseRequestId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ParentCode { get; set; }
        public int Quantity { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string SalesBy { get; set; }
        public string ManufactureId { get; set; }
        public System.DateTime RequireDate { get; set; }
        public string UnitName { get; set; }
        public bool Status { get; set; }
        public string PRCode { get; set; }
        public decimal QuotaPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportProfileProduct> ImportProfileProducts { get; set; }
        public virtual PurchaseRequest PurchaseRequest { get; set; }
    }
}
