//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationProduct
    {
        public string Id { get; set; }
        public string QuotationId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ObjectId { get; set; }
        public int ObjectType { get; set; }
        public string IndustryId { get; set; }
        public string ManufactureId { get; set; }
        public string UnitId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
