//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SketchAttachHistory
    {
        public string Id { get; set; }
        public string SketchAttachId { get; set; }
        public decimal FileSize { get; set; }
        public string Path { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual SketchAttach SketchAttach { get; set; }
    }
}
