//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solution()
        {
            this.ProjectSolutions = new HashSet<ProjectSolution>();
            this.SolutionAttaches = new HashSet<SolutionAttach>();
            this.SolutionFeatures = new HashSet<SolutionFeature>();
            this.SolutionImages = new HashSet<SolutionImage>();
            this.SolutionProducts = new HashSet<SolutionProduct>();
            this.SolutionOldVersions = new HashSet<SolutionOldVersion>();
        }
    
        public string Id { get; set; }
        public string SolutionGroupId { get; set; }
        public string SBUBusinessId { get; set; }
        public string DepartmentBusinessId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string CustomerId { get; set; }
        public string EndCustomerId { get; set; }
        public string BusinessUserId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string SolutionMaker { get; set; }
        public string SBUSolutionMakerId { get; set; }
        public string DepartmentSolutionMakerId { get; set; }
        public int Status { get; set; }
        public decimal SaleNoVAT { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string DepartmentId { get; set; }
        public int Index { get; set; }
        public int CurentVersion { get; set; }
        public string MechanicalMaker { get; set; }
        public string ElectricMaker { get; set; }
        public string ElectronicMaker { get; set; }
        public bool Design3DExist { get; set; }
        public bool Design2DExist { get; set; }
        public bool ExplanExist { get; set; }
        public bool DMVTExist { get; set; }
        public bool FCMExist { get; set; }
        public bool TSTKExist { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsEnoughDocument { get; set; }
        public string BusinessDomain { get; set; }
        public string CustomerRequirementId { get; set; }
        public string JobId { get; set; }
        public string ApplicationId { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSolution> ProjectSolutions { get; set; }
        public virtual SolutionGroup SolutionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolutionAttach> SolutionAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolutionFeature> SolutionFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolutionImage> SolutionImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolutionProduct> SolutionProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolutionOldVersion> SolutionOldVersions { get; set; }
    }
}
