//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTimeStandard
    {
        public string Id { get; set; }
        public string EmployeeId { get; set; }
        public decimal TimeStandard { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string SBUId { get; set; }
        public string DepartmentId { get; set; }
        public string TaskId { get; set; }
        public string ModuleGroupId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
