//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskWorkType
    {
        public string Id { get; set; }
        public string TaskId { get; set; }
        public string WorkTypeRId { get; set; }
        public string WorkTypeAId { get; set; }
        public string WorkTypeSId { get; set; }
        public string WorkTypeCId { get; set; }
        public string WorlTypeIId { get; set; }
        public string SBUId { get; set; }
        public string DepartmentId { get; set; }
        public int Index { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
