//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDiary
    {
        public string Id { get; set; }
        public string DepartmentId { get; set; }
        public string SBUId { get; set; }
        public string EmployeeId { get; set; }
        public string Name { get; set; }
        public string ProjectId { get; set; }
        public string ObjectId { get; set; }
        public System.DateTime WorkDate { get; set; }
        public decimal TotalTime { get; set; }
        public string Address { get; set; }
        public int Done { get; set; }
        public int ObjectType { get; set; }
        public string Note { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual SBU SBU { get; set; }
    }
}
