//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTS.Common.Resource.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thư mục.
        /// </summary>
        public static string DesignStructure {
            get {
                return ResourceManager.GetString("DesignStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File trong thư mục.
        /// </summary>
        public static string DesignStructureFile {
            get {
                return ResourceManager.GetString("DesignStructureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãng sản xuất.
        /// </summary>
        public static string Manufacture {
            get {
                return ResourceManager.GetString("Manufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật liệu điện, điện tử.
        /// </summary>
        public static string MaterialElectronic {
            get {
                return ResourceManager.GetString("MaterialElectronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm vật tư chức năng.
        /// </summary>
        public static string MaterialGroup {
            get {
                return ResourceManager.GetString("MaterialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm vật tư TPA.
        /// </summary>
        public static string MaterialGroupTPA {
            get {
                return ResourceManager.GetString("MaterialGroupTPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật liệu cơ khí.
        /// </summary>
        public static string MaterialMechanical {
            get {
                return ResourceManager.GetString("MaterialMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module nguồn.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm module nguồn.
        /// </summary>
        public static string ModuleGroup {
            get {
                return ResourceManager.GetString("ModuleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật liệu.
        /// </summary>
        public static string RawMaterial {
            get {
                return ResourceManager.GetString("RawMaterial", resourceCulture);
            }
        }
    }
}
