const provinceMap = [
  '',
  'VN-HN',
  'Hà Giang',
  '',
  'Cao Bằng',
  '',
  'Bắc Kạn',
  '',
  'Tuyên Quang',
  '',
  'Lào Cai',
  'Điện Biên',
  'Lai Châu',
  '',
  'Sơn La',
  'Yên Bái',
  '',
  'Hòa Bình',
  '',
  'Thái Nguyên',
  'Lạng Sơn',
  '',
  'Quảng Ninh',
  '',
  'Bắc Giang',
  'Phú Thọ',
  'Vĩnh Phúc',
  'Bắc Ninh',
  '',
  '',
  'Hải Dương',
  'Hải Phòng City',
  '',
  'Hưng Yên',
  'Thái Bình',
  'Hà Nam',
  'Nam Định',
  'Ninh Bình',
  'Thanh Hóa',
  '',
  'Nghệ An',
  '',
  'Hà Tĩnh',
  '',
  'Quảng Bình',
  'Quảng Trị',
  'Thừa Thiên–Huế',
  '',
  'Đà Nẵng City',
  'Quảng Nam',
  '',
  'Quảng Ngãi',
  'Bình Định',
  '',
  'Phú Yên',
  '',
  'Khánh Hòa',
  '',
  'Ninh Thuận',
  '',
  'Bình Thuận',
  '',
  'Kon Tum',
  '',
  'Gia Lai',
  '',
  'Đắk Lắk',
  'VN-72',
  'Lâm Đồng',
  '',
  'Bình Phước',
  '',
  'Tây Ninh',
  '',
  'Bình Dương',
  'Đồng Nai',
  '',
  'Bà Rịa–Vũng Tàu',
  '',
  'VN-SG',
  'Long An',
  '',
  'Tiền Giang',
  'Bến Tre',
  'Trà Vinh',
  '',
  'Vĩnh Long',
  'Đồng Tháp',
  '',
  'An Giang',
  '',
  'Kiên Giang',
  'VN-CT',
  'Hậu Giang',
  'Sóc Trăng',
  'VN-55',
  'Cà Mau',
];
const originMap = [
  ['State', 'Value'],
  ['Bắc Giang', 0],
  ['Bắc Kạn', 0],
  ['Cao Bằng', 0],
  ['Hà Giang', 0],
  ['Lạng Sơn', 0],
  ['Phú Thọ', 0],
  ['Quảng Ninh', 0],
  ['Thái Nguyên', 0],
  ['Tuyên Quang', 0],
  ['Lào Cai', 0],
  ['Yên Bái', 0],
  ['Điện Biên', 0],
  ['Hòa Bình', 0],
  ['Lai Châu', 0],
  ['Sơn La', 0],
  ['Bắc Ninh', 0],
  ['Hà Nam', 0],
  ['Hải Dương', 0],
  ['Hưng Yên', 0],
  ['Nam Định', 0],
  ['Ninh Bình', 0],
  ['Thái Bình', 0],
  ['Vĩnh Phúc', 0],
  ['VN-HN', 0],
  ['Hải Phòng City', 0],
  ['Hà Tĩnh', 0],
  ['Nghệ An', 0],
  ['Quảng Bình', 0],
  ['Quảng Trị', 0],
  ['Thanh Hóa', 0],
  ['Thừa Thiên–Huế', 0],
  ['Đắk Lắk', 0],
  ['VN-72', 0],
  ['Gia Lai', 0],
  ['Kon Tum', 0],
  ['Lâm Đồng', 0],
  ['Bình Định', 0],
  ['Bình Thuận', 0],
  ['Khánh Hòa', 0],
  ['Ninh Thuận', 0],
  ['Phú Yên', 0],
  ['Quảng Nam', 0],
  ['Quảng Ngãi', 0],
  ['Đà Nẵng City', 0],
  ['Bà Rịa–Vũng Tàu', 0],
  ['Bình Dương', 0],
  ['Bình Phước', 0],
  ['Đồng Nai', 0],
  ['Tây Ninh', 0],
  ['VN-SG', 0],
  ['An Giang', 0],
  ['VN-55', 0],
  ['Bến Tre', 0],
  ['Cà Mau', 0],
  ['Đồng Tháp', 0],
  ['Hậu Giang', 0],
  ['Kiên Giang', 0],
  ['Long An', 0],
  ['Sóc Trăng', 0],
  ['Tiền Giang'],
  ['Trà Vinh', 0],
  ['Vĩnh Long', 0],
  ['VN-CT', 0],
  ['VN-DN', 0],
];
export { provinceMap, originMap };
