import { NtsNavigation } from './navigationitem';

export const navigation: NtsNavigation[] = [
  {
    id: 'vattu',
    title: 'VẬT TƯ',
    icon: 'toolbox',
    type: 'collapsable',
    ismdi: true,
    permission: [
      'F000000',
      'F000100',
      'F000200',
      'F000300',
      'F000400',
      'F000500',
      'F000600',
      'F000700',
      'F000900',
      'F001100',
    ],
    children: [
      {
        id: 'vattu',
        title: 'Vật tư',
        type: 'item',
        permission: ['F000000'],
        url: '/vat-tu/quan-ly-vat-tu',
      },
      {
        id: 'nhomvattu',
        title: 'Nhóm vật tư theo chức năng',
        type: 'item',
        permission: ['F000100'],
        url: '/vat-tu/nhom-vat-tu-chuc-nang',
      },
      {
        id: 'nhomvattu',
        title: 'Nhóm vật tư TPA',
        type: 'item',
        permission: ['F000200'],
        url: '/vat-tu/nhom-vat-tu-tpa',
      },
      {
        id: 'cauhinh',
        title: 'Cấu hình thông số vật tư',
        type: 'item',
        permission: ['F000300'],
        url: '/vat-tu/cau-hinh-thong-so-vat-tu',
      },
      {
        id: 'nhomvattuphitieuchuan',
        title: 'Nhóm vật tư phi tiêu chuẩn',
        type: 'item',
        permission: ['F000400'],
        url: '/vat-tu/nhom-vat-tu-phi-tieu-chuan',
      },
      {
        id: 'hangsanxuat',
        title: 'Hãng sản xuất',
        type: 'item',
        permission: ['F000500'],
        url: '/vat-tu/hang-san-xuat',
      },
      {
        id: 'donvi',
        title: 'Đơn vị tính',
        type: 'item',
        permission: ['F000600'],
        url: '/vat-tu/don-vi',
      },
      {
        id: 'vatlieu',
        title: 'Vật liệu',
        type: 'item',
        permission: ['F000700'],
        url: '/vat-tu/vat-lieu',
      },

      {
        id: 'vttt',
        title: 'Vật tư tương tự',
        type: 'item',
        permission: ['F000900'],
        url: '/vat-tu/vat-tu-tuong-tu',
      },
      {
        id: 'chmvt',
        title: ' Định Nghĩa Mã Vật Tư PM Tạo',
        type: 'item',
        permission: ['F001100'],
        url: '/vat-tu/cau-hinh-ma-vat-tu',
      },
      // {
      //     id: 'chmvt',
      //     title: ' Test Search',
      //     type: 'item',
      //     permission: [],
      //     url: '/vat-tu/test-search'
      // },
    ],
  },
  {
    id: 'module',
    title: 'MODULE',
    icon: 'memory',
    type: 'collapsable',
    permission: [
      'F020100',
      'F020300',
      'F020500',
      'F020700',
      'F091200',
      'F110300',
    ],
    children: [
      {
        id: 'modulenguon',
        title: 'Module nguồn',
        type: 'item',
        permission: ['F020100'],
        url: '/module/quan-ly-module',
      },
      {
        id: 'tieuchikiemtra',
        title: 'Tiêu chí kiểm tra',
        type: 'item',
        permission: ['F020300'],
        url: '/module/quan-ly-tieu-chi-kiem-tra',
      },
      {
        id: 'tieuchuansanpham',
        title: 'Tiêu chuẩn sản phẩm',
        type: 'item',
        permission: ['F020500'],
        url: '/module/quan-ly-tieu-chuan-san-pham',
      },
      {
        id: 'tinhnang',
        title: 'Tính năng',
        type: 'item',
        permission: ['F020700'],
        url: '/module/quan-ly-tinh-nang',
      },
      {
        id: 'nganh',
        title: 'Ngành hàng',
        type: 'item',
        permission: ['F091200'],
        url: '/module/quan-ly-nganh',
      },
      {
        id: 'congdoan',
        title: 'Công đoạn sản xuất',
        type: 'item',
        permission: ['F110300'],
        url: '/module/cong-doan-san-xuat',
      },
    ],
  },
  {
    id: 'device',
    title: 'THIẾT BỊ',
    icon: 'devices_other',
    type: 'collapsable',
    permission: ['F030400', 'F110800'],
    children: [
      // {
      //     id: 'quanlynhomthietbi',
      //     title: 'Quản lý nhóm thiết bị',
      //     type: 'item',
      //     permission: [],
      //     url: '/thiet-bi/quan-ly-nhom-thiet-bi'
      // },
      {
        id: 'quanlythietbi',
        title: 'Quản lý thiết bị',
        type: 'item',
        permission: ['F030400'],
        url: '/thiet-bi/quan-ly-thiet-bi',
      },
      {
        id: 'quanlythietbitieuchuan',
        title: 'Quản lý thiết bị nhập khẩu',
        type: 'item',
        permission: ['F110800'],
        url: '/thiet-bi/quan-ly-thiet-bi-nhap-khau',
      },
      {
        id: 'quanlythietbitieuchuan',
        title: 'Chủng loại hàng hóa',
        type: 'item',
        permission: ['F110850'],
        url: '/thiet-bi/chung-loai-hang-hoa',
      },
    ],
  },
  {
    id: 'practice',
    title: 'THỰC HÀNH',
    icon: 'computer',
    type: 'collapsable',
    permission: [
      'F040700',
      'F040500',
      'F040000',
      'F040100',
      'F040200',
      'F040300',
    ],
    children: [
      {
        id: 'quanlybaithuchanh',
        title: 'Quản lý bài thực hành/công đoạn',
        type: 'item',
        permission: ['F040700'],
        url: '/thuc-hanh/quan-ly-bai-thuc-hanh',
      },
      {
        id: 'quanlykynang',
        title: 'Quản lý kỹ năng BTH/ứng dụng',
        type: 'item',
        permission: ['F040500'],
        url: '/thuc-hanh/quan-ly-ky-nang',
      },
      {
        id: 'quanlytrinhdo',
        title: 'Quản lý trình độ',
        type: 'item',
        permission: ['F040000'],
        url: '/thuc-hanh/quan-ly-trinh-do',
      },
      {
        id: 'quanlychuyenmon',
        title: 'Quản lý chuyên môn',
        type: 'item',
        permission: ['F040100'],
        url: '/thuc-hanh/quan-ly-chuyen-mon',
      },
      // {
      //     id: 'quanlynhomkynang',
      //     title: 'Quản lý nhóm kỹ năng',
      //     type: 'item',
      //     permission: [],
      //     url: '/thuc-hanh/quan-ly-nhom-ky-nang'
      // },
      {
        id: 'quanlydonvicongtac',
        title: 'Quản lý đơn vị công tác',
        type: 'item',
        permission: ['F040200'],
        url: '/thuc-hanh/quan-ly-don-vi-cong-tac',
      },
      {
        id: 'quanlychuyengia',
        title: 'Quản lý chuyên gia',
        type: 'item',
        permission: ['F040300'],
        url: '/thuc-hanh/quan-ly-chuyen-gia',
      },
    ],
  },
  {
    id: 'jobgroup',
    title: 'PHÒNG HỌC/LINE SẢN XUẤT',
    icon: 'school',
    type: 'collapsable',
    permission: ['F050000', 'F050100', 'F050300', 'F050500'],
    children: [
      {
        id: 'quanlymonhoc',
        title: 'Quản lý môn học',
        type: 'item',
        permission: ['F050000'],
        url: '/phong-hoc/quan-ly-mon-hoc',
      },
      {
        id: 'quanlychuongtrinhdaotao',
        title: 'Quản lý chương trình đào tạo',
        type: 'item',
        permission: ['F050100'],
        url: '/phong-hoc/quan-ly-chuong-trinh-dao-tao',
      },
      {
        id: 'quanlyphonghoc',
        title: 'Quản lý phòng học/line sản xuất',
        type: 'item',
        permission: ['F050300'],
        url: '/phong-hoc/quan-ly-phong-hoc',
      },
      {
        id: 'quanlynghe',
        title: 'Quản lý nghề',
        type: 'item',
        permission: ['F050500'],
        url: '/phong-hoc/quan-ly-nghe',
      },
    ],
  },
  {
    id: 'project',
    title: 'DỰ ÁN',
    icon: 'assignment',
    type: 'collapsable',
    permission: [
      'F060000',
      'F060400',
      'F060500',
      'F060600',
      'F060700',
      'F110000',
      'F060800',
      'F060900',
    ],
    children: [
      {
        id: 'quanlyduan',
        title: 'Quản lý dự án',
        type: 'item',
        permission: ['F060000'],
        url: '/du-an/quan-ly-du-an',
      },
      {
        id: 'vandetontai',
        title: 'Vấn đề tồn đọng',
        type: 'item',
        permission: ['F060400'],
        url: '/du-an/quan-ly-van-de',
      },
      {
        id: 'quanlykehoach',
        title: 'Quản lý kế hoạch',
        type: 'item',
        permission: ['F110700'],
        url: '/du-an/quan-ly-ke-hoach',
      },
      {
        id: 'thoigianlamviec',
        title: 'Thời gian làm việc',
        type: 'item',
        permission: ['F060800'],
        url: '/du-an/thoi-gian-lam-viec',
      },
      {
        id: 'kehoachthietke',
        title: 'Tổng hợp kế hoạch thiết kế',
        type: 'item',
        permission: ['F060900'],
        url: '/du-an/tong-hop-ke-hoach-thiet-ke',
      },

      {
        id: 'logthoigianlamviec',
        title: 'Log thời gian làm việc',
        type: 'item',
        permission: ['F060800'],
        url: '/du-an/log-thoi-gian-lam-viec',
      },
      {
        id: 'thietbicananpham',
        title: 'Thiết bị cần ấn phẩm',
        type: 'item',
        permission: ['F060000'],
        url: '/du-an/thiet-bi-can-an-pham',
      },
      {
        id: 'danhmuc',
        title: 'Danh mục định nghĩa',
        type: 'collapsable',
        permission: [],
        children: [
          {
            id: 'cauhinhthongtinngaynghi',
            title: 'Cấu hình thông tin ngày nghỉ',
            type: 'item',
            permission: ['F110000'],
            url: '/du-an/cau-hinh-thong-tin-ngay-nghi',
          },
          {
            id: 'vitricongviec',
            title: 'Vị trí công việc trong dự án',
            type: 'item',
            permission: ['F060000'],
            url: '/du-an/vi-tri-cong-viec',
          },
          {
            id: 'cauhinhcongviectheonhommodule',
            title: 'Cấu hình công việc theo nhóm module ',
            type: 'item',
            permission: ['F060500'],
            url: '/du-an/cau-hinh-cong-viec-theo-nhom-module',
          },
          {
            id: 'thoigiantieuchuanchotungcongviec',
            title: 'Thời gian tiêu chuẩn cho từng công việc ',
            type: 'item',
            permission: ['F060600'],
            url: '/du-an/thoi-gian-tieu-chuan-cho-tung-cong-viec',
          },
        ],
      },
    ],
  },

  {
    id: 'customer',
    title: 'KHÁCH HÀNG-NCC',
    icon: 'assignment',
    type: 'collapsable',
    permission: ['F060100', 'F060200', 'F000800'],
    children: [
      {
        id: 'quanlyloaikhachhang',
        title: 'Quản lý loại khách hàng',
        type: 'item',
        permission: ['F060100'],
        url: '/du-an/quan-ly-loai-khach-hang',
      },
      {
        id: 'quanlykhachhang',
        title: 'Quản lý khách hàng',
        type: 'item',
        permission: ['F060200'],
        url: '/du-an/quan-ly-khach-hang',
      },
      {
        id: 'ncc',
        title: 'Nhà cung cấp',
        type: 'item',
        permission: ['F000800'],
        url: '/vat-tu/nha-cung-cap',
      },
    ],
  },

  {
    id: 'solution',
    title: 'GIẢI PHÁP',
    icon: 'wb_incandescent',
    type: 'collapsable',
    permission: ['F070000'],
    children: [
      {
        id: 'giaiphap',
        title: 'Giải pháp',
        type: 'item',
        permission: ['F070000'],
        url: '/giai-phap/quan-ly-giai-phap',
      },
      {
        id: 'yeucaukhachhang',
        title: 'Yêu cầu khách hàng',
        type: 'item',
        permission: [],
        url: '/giai-phap/yeu-cau-khach-hang',
      },
      {
        id: 'meeting',
        title: 'Meeting',
        type: 'item',
        permission: [],
        url: '/giai-phap/meeting',
      },

      {
        id: 'projectphase',
        title: 'Quản lý giai đoạn của dự án',
        type: 'item',
        permission: [],
        url: '/giai-phap/quan-ly-giai-doan-cua-du-an',
      },
      {
        id: 'tonghopbaogia',
        title: 'Tổng hợp báo giá',
        type: 'item',
        permission: [],
        url: '/giai-phap/tong-hop-bao-gia',
      },
    ],
  },
  {
    id: 'employees',
    title: 'NHÂN SỰ',
    icon: 'people',
    type: 'collapsable',
    permission: [
      'F030000',
      'F030100',
      'F030200',
      'F080000',
      'F080100',
      'F080200',
      'F080400',
      'F080500',
      'F080600',
      'F080800',
      'F110101',
      'F080900',
      'F110400',
      'F110600',
    ],
    children: [
      {
        id: 'quanlynhanvien',
        title: 'Quản lý nhân viên',
        type: 'item',
        permission: ['F080000'],
        url: '/nhan-vien/quan-ly-nhan-vien',
      },
      {
        id: 'nhatkycongviec',
        title: 'Nhật ký công việc',
        type: 'item',
        permission: ['F080800'],
        url: '/nhan-vien/nhat-ky-cong-viec',
      },
      {
        id: 'tongthoigianthuchien',
        title: 'Tổng hợp thời gian thực hiện',
        type: 'item',
        permission: ['F110100'],
        url: '/nhan-vien/tong-thoi-gian-thuc-hien',
      },
      {
        id: 'quaylycongiviec',
        title: 'Quản lý công việc',
        type: 'item',
        permission: ['F121550'],
        url: '/nhan-vien/quan-ly-cong-viec',
      },
      {
        id: 'quanlyloaicongviec',
        title: 'Quản lý vị trí công việc',
        type: 'item',
        permission: ['F080500'],
        url: '/nhan-vien/quan-ly-vi-tri-cong-viec',
      },
      {
        id: 'chuonhtrinhdaotao',
        title: 'Chương trình đào tạo',
        type: 'item',
        permission: ['F080600'],
        url: '/nhan-vien/chuong-trinh-dao-tao',
      },
      {
        id: 'quanlykhoahoc',
        title: 'Quản lý khóa học',
        type: 'item',
        permission: ['F080200'],
        url: '/nhan-vien/quan-ly-khoa-hoc',
      },
      {
        id: 'quanlySBU',
        title: 'Quản lý SBU',
        type: 'item',
        permission: ['F030200'],
        url: '/nhan-vien/quan-ly-SBU',
      },
      {
        id: 'quanlyphongban',
        title: 'Quản lý phòng ban',
        type: 'item',
        permission: ['F030000'],
        url: '/nhan-vien/quan-ly-phong-ban',
      },
      {
        id: 'quanlynhomquyen',
        title: 'Quản lý nhóm quyền',
        type: 'item',
        permission: ['F080900'],
        url: '/nhan-vien/quan-ly-nhom-quyen',
      },
      {
        id: 'quanlykynang',
        title: 'Quản lý kỹ năng/kiến thức nhân viên',
        type: 'item',
        permission: ['F080400'],
        url: '/nhan-vien/quan-ly-ky-nang',
      },
      {
        id: 'quanlycauhoi',
        title: 'Quản lý câu hỏi',
        type: 'item',
        permission: ['F030100'],
        url: '/nhan-vien/quan-ly-cau-hoi',
      },
      {
        id: 'hesonanglucnhanvien',
        title: 'Hệ số năng lực nhân viên',
        type: 'item',
        permission: ['F110600'],
        url: '/nhan-vien/he-so-nang-luc-nhan-vien',
      },
      {
        id: 'lichsuthaotac',
        title: 'Lịch sử thao tác',
        type: 'item',
        permission: ['F110500'],
        url: '/nhan-vien/lich-su-thao-tac',
      },
      {
        id: 'danhmuc',
        title: 'Danh mục định nghĩa',
        type: 'collapsable',
        permission: [],
        children: [
          {
            id: 'quaylyketquadaura',
            title: 'Quản lý kết quả đầu vào/ra',
            type: 'item',
            permission: ['F121470'],
            url: '/nhan-vien/quan-ly-ket-qua-dau-ra',
          },
          {
            id: 'quanlynhomnhanvien',
            title: 'Quản lý nhóm nhân viên',
            type: 'item',
            permission: ['F080100'],
            url: '/nhan-vien/quan-ly-nhom-nhan-vien',
          },
          {
            id: 'quanlymucluong',
            title: 'Quản lý mức lương',
            type: 'item',
            permission: ['F121500'],
            url: '/nhan-vien/quan-ly-muc-luong',
          },
          {
            id: 'quanlynhomluong',
            title: 'Quản lý nhóm lương',
            type: 'item',
            permission: ['F121510'],
            url: '/nhan-vien/quan-ly-nhom-luong',
          },
          {
            id: 'quanlytypeluong',
            title: 'Quản lý ngạch lương',
            type: 'item',
            permission: ['F121520'],
            url: '/nhan-vien/quan-ly-ngach-luong',
          },
          {
            id: 'quanlychucvu',
            title: 'Quản lý chức vụ',
            type: 'item',
            permission: ['F030100'],
            url: '/nhan-vien/quan-ly-chuc-vu',
          },
          {
            id: 'quanlyloaihopdonglaodong',
            title: 'Quản lý loại hợp đồng',
            type: 'item',
            permission: ['F120950'],
            url: '/nhan-vien/quan-ly-loai-hop-dong-lao-dong',
          },
          {
            id: 'quanlynoilamviec',
            title: 'Quản lý nơi làm việc',
            type: 'item',
            permission: ['F121000'],
            url: '/nhan-vien/quan-ly-noi-lam-viec',
          },
          {
            id: 'quanlylydodieuchinhthunhap',
            title: 'Quản lý lý do điều chỉnh thu nhập',
            type: 'item',
            permission: ['F121050'],
            url: '/nhan-vien/quan-ly-ly-do-dieu-chinh-thu-nhap',
          },
          {
            id: 'quanlylydodieuchinhthunhap',
            title: 'Quản lý lý do điều chỉnh BHXH',
            type: 'item',
            permission: ['F121100'],
            url: '/nhan-vien/quan-ly-ly-do-dieu-chinh-bhxh',
          },
          {
            id: 'quanlylydonghiviec',
            title: 'Quản lý lý do nghỉ việc',
            type: 'item',
            permission: ['F121150'],
            url: '/nhan-vien/quan-ly-ly-do-nghi-viec',
          },
          {
            id: 'quanlynganhang',
            title: 'Quản lý ngân hàng',
            type: 'item',
            permission: ['F121200'],
            url: '/nhan-vien/quan-ly-ngan-hang',
          },
          {
            id: 'quanlymucdongbaohiem',
            title: 'Quản lý mức đóng bảo hiểm',
            type: 'item',
            permission: ['F121250'],
            url: '/nhan-vien/quan-ly-muc-dong-bao-hiem',
          },
          {
            id: 'quanlyxeploai',
            title: 'Quản lý xếp loại',
            type: 'item',
            permission: ['F110400'],
            url: '/nhan-vien/quan-ly-xep-loai',
          },
        ],
      },
    ],
  },
  {
    id: 'document',
    title: 'TÀI LIỆU',
    icon: 'folder',
    type: 'collapsable',
    permission: ['F121300', 'F121350', 'F121400'],
    children: [
      {
        id: 'tailieu',
        title: 'Quản lý tài liệu',
        type: 'item',
        permission: ['F121300'],
        url: '/tai-lieu/quan-ly-tai-lieu',
      },
      {
        id: 'tracuutailieu',
        title: 'Tra cứu tài liệu',
        type: 'item',
        permission: ['F121350'],
        url: '/tai-lieu/tra-cuu-tai-lieu',
      },
      {
        id: 'tailieu',
        title: 'Quản lý loại tài liệu',
        type: 'item',
        permission: ['F121400'],
        url: '/tai-lieu/quan-ly-loai-tai-lieu',
      },
    ],
  },
  {
    id: 'recruitment',
    title: 'TUYỂN DỤNG',
    icon: 'perm_contact_calendar',
    type: 'collapsable',
    permission: [],
    children: [
      {
        id: 'yeucautuyendung',
        title: 'Yêu cầu tuyển dụng',
        type: 'item',
        permission: [],
        url: '/tuyen-dung/yeu-cau-tuyen-dung',
      },
      {
        id: 'quanlyungtuyen',
        title: 'Hồ sơ ứng viên',
        type: 'item',
        permission: [],
        url: '/tuyen-dung/ung-tuyen',
      },
      {
        id: 'quanlyungvien',
        title: 'Ứng viên đạt',
        type: 'item',
        permission: [],
        url: '/tuyen-dung/ho-so-ung-vien',
      },
      {
        id: 'quanlyphongvan',
        title: 'Phỏng vấn',
        type: 'item',
        permission: [],
        url: '/tuyen-dung/phong-van',
      },
      {
        id: 'kenhtuyendung',
        title: 'Kênh tuyển dụng',
        type: 'item',
        permission: [],
        url: '/tuyen-dung/kenh-tuyen-dung',
      },
    ],
  },
  {
    id: 'tools',
    title: 'TOOLS',
    icon: 'card_travel',
    type: 'collapsable',
    permission: [
      'F090000',
      'F090100',
      'F090600',
      'F091000',
      'F090700',
      'F090800',
      'F090900',
      'F091100',
      'F110200',
      'F050312',
    ],
    children: [
      {
        id: 'taocautructhumuc',
        title: 'Tạo cấu trúc thư mục',
        type: 'item',
        permission: ['F090000'],
        url: '/tools/tao-cau-truc-thu-muc',
      },
      {
        id: 'taobieumau',
        title: 'Tạo biểu mẫu',
        type: 'item',
        permission: ['F090100'],
        url: '/tools/tao-bieu-mau',
      },
      {
        id: 'caidatdinhnghiathumuc',
        title: 'Cài đặt định nghĩa thư mục',
        type: 'item',
        permission: ['F090600'],
        url: '/tools/dinh-nghia-thu-muc',
      },
      {
        id: 'scanfile',
        title: 'Đổi tên file Scan',
        type: 'item',
        permission: ['F091000'],
        url: '/tools/scan-file',
      },
      {
        id: 'kiemtracautructhietke',
        title: 'Kiểm tra dữ liệu thiết kế',
        type: 'item',
        permission: ['F090700'],
        url: '/tools/kiem-tra-cau-truc-thiet-ke',
      },
      {
        id: 'phanbodulieu',
        title: 'Cấu trúc phân bổ dữ liệu',
        type: 'item',
        permission: ['F090800'],
        url: '/tools/phan-bo-du-lieu',
      },
      {
        id: 'downloadlistmodule',
        title: 'Download tài liệu thiết kế',
        type: 'item',
        permission: ['F090900'],
        url: '/tools/download-danh-sach-module',
      },
      {
        id: 'downloaddmvtsap',
        title: 'Download DMVT Import SAP',
        type: 'item',
        permission: ['F091100'],
        url: '/tools/download-dmvt-sap',
      },
      {
        id: 'kiemtragiavattu',
        title: 'Kiểm tra giá vật tư',
        type: 'item',
        permission: ['F110200'],
        url: '/tools/kiem-tra-gia-vat-tu',
      },
      {
        id: 'cauhinh',
        title: 'Cấu hình',
        type: 'item',
        permission: ['F110450'],
        url: '/tools/cau-hinh',
      },
      {
        id: 'toolhotro',
        title: 'Tool hỗ trợ - phòng học',
        type: 'item',
        permission: ['F050312'],
        url: '/tools/tool-ho-tro',
      },
    ],
  },
  {
    id: 'reports',
    title: 'BÁO CÁO',
    icon: 'equalizer',
    type: 'collapsable',
    permission: [
      'F100001',
      'F100002',
      'F100003',
      'F100004',
      'F100005',
      'F100006',
      'F100007',
      'F100012',
      'F100008',
      'F100009',
      'F100010',
      'F100011',
      'F100014',
      'F100015',
      'F100016',
    ],
    children: [
      {
        id: 'baocaovandetondong',
        title: 'Báo cáo vấn đề tồn đọng',
        type: 'item',
        permission: ['F100014'],
        url: '/bao-cao/bao-cao-van-de-ton-dong',
      },
      {
        id: 'baocaovandetondong',
        title: 'Báo cáo tiến độ vấn đề tồn đọng',
        type: 'item',
        permission: ['F100015'],
        url: '/bao-cao/bao-cao-tien-do-van-de-ton-dong',
      },
      {
        id: 'baocaoyeutoanhhuong',
        title: 'Báo cáo yếu tố ảnh hưởng',
        type: 'item',
        permission: ['F100017'],
        url: '/bao-cao/bao-cao-yeu-to-anh-huong',
      },
      {
        id: 'baocaotiendotrienkhaiduan',
        title: 'Báo cáo tiến độ triển khai dự án',
        type: 'item',
        permission: ['F100016'],
        url: '/bao-cao/bao-cao-tien-do-trien-khai-du-an',
      },
      {
        id: 'logthoigianlamviec',
        title: 'Báo cáo thu tiền dự án',
        type: 'item',
        permission: ['F100018'],
        url: '/du-an/bao-cao-thu-tien-du-an',
      },
      {
        id: 'danhmuc',
        title: 'Temp',
        type: 'collapsable',
        permission: [],
        children: [
          {
            id: 'dubaonhansutuonglai',
            title: 'Dự báo nhân sự tương lai',
            type: 'item',
            permission: ['F100001'],
            url: '/bao-cao/du-bao-nhan-su-tuong-lai',
          },
          {
            id: 'currentquanlityreport',
            title: 'Dự báo dự án tương lai',
            type: 'item',
            permission: ['F100002'],
            url: '/bao-cao/bao-cao-du-an-tuong-lai',
          },
          {
            id: 'employeepresent',
            title: 'Báo cáo nhân viên hiện tại',
            type: 'item',
            permission: ['F100003'],
            url: '/bao-cao/bao-cao-nhan-vien-hien-tai',
          },
          {
            id: 'datamaster',
            title: 'Tổng hợp dữ liệu thư viện',
            type: 'item',
            permission: ['F100004'],
            url: '/bao-cao/bao-cao-master-thu-vien',
          },
          {
            id: 'masterEmployeeLevel',
            title: 'Tổng hợp dữ liệu vị trí công việc',
            type: 'item',
            permission: ['F100005'],
            url: '/bao-cao/bao-cao-master-level-nhan-su',
          },
          {
            id: 'masterEmployeeLevel',
            title: 'Tổng hợp dữ liệu nhân sự',
            type: 'item',
            permission: ['F100006'],
            url: '/bao-cao/bao-cao-master-nhan-su',
          },
          {
            id: 'canhbaochiphi',
            title: 'Cảnh báo chi phí',
            type: 'item',
            permission: ['F100007'],
            url: '/bao-cao/canh-bao-chi-phi',
          },
          {
            id: 'baocaochiphihientai',
            title: 'Báo cáo chi phí hiện tại',
            type: 'item',
            permission: ['F100012'],
            url: '/bao-cao/canh-bao-chi-phi-hien-tai',
          },
          {
            id: 'baocaochatluonghientai',
            title: 'Báo cáo chất lượng hiện tại',
            type: 'item',
            permission: ['F100008'],
            url: '/bao-cao/bao-cao-chat-luong-hien-tai',
          },
          {
            id: 'baocaotinhtrangvattu',
            title: 'Báo cáo tình trạng vật tư',
            type: 'item',
            permission: ['F100009'],
            url: '/bao-cao/bao-cao-tinh-trang-vat-tu',
          },
          {
            id: 'baocaotinhtrangmodule',
            title: 'Báo cáo tình trạng module',
            type: 'item',
            permission: ['F100010'],
            url: '/bao-cao/bao-cao-tinh-trang-module',
          },
          {
            id: 'baocaotinhtrangproduct',
            title: 'Báo cáo tình trạng thiết bị',
            type: 'item',
            // permission: ['F100010'],
            url: '/bao-cao/bao-cao-tinh-trang-product',
          },
          {
            id: 'baocaoungdunghientai',
            title: 'Báo cáo ứng dụng hiện tại',
            type: 'item',
            permission: ['F100011'],
            url: '/bao-cao/bao-cao-ung-dung-hien-tai',
          },
          {
            id: 'reportsalesbusiness',
            title: 'Báo cáo theo Doanh số',
            type: 'item',
            permission: ['F100012'],
            url: '/bao-cao/report-sales-business',
          },
          {
            id: 'dashboardnhansu',
            title: 'Dashboard nhân sự',
            type: 'item',
            permission: ['F061000'],
            url: '/du-an/dashboard-employee',
          },
          {
            id: 'dashboardduan',
            title: 'Dashboard dự án',
            type: 'item',
            permission: ['F061100'],
            url: '/du-an/dashboard-project',
          },
        ],
      },
    ],
  },
  {
    id: 'sale',
    title: 'KINH DOANH',
    icon: 'store',
    type: 'collapsable',
    permission: [
      'F110850',
      'F120000',
      'F120100',
      'F120101',
      'F120200',
      'F120300',
      'F120400',
      'F120500',
    ],
    children: [
      {
        id: 'them_xuat_du',
        title: 'Thêm xuất giữ',
        type: 'item',
        permission: ['F120101'],
        url: '/kinh-doanh/them-moi-xuat-giu',
      },
      {
        id: 'danhnhachxuatgiu',
        title: 'Quản lý xuất giữ',
        type: 'item',
        permission: ['F120100'],
        url: '/kinh-doanh/danh-sach-xuat-giu',
      },
      {
        id: 'lichsuxuatgiu',
        title: 'Lịch sử xuất giữ',
        type: 'item',
        permission: ['F120200'],
        url: '/kinh-doanh/lich-su-xuat-giu',
      },
      {
        id: 'sanphamchokinhdoanh',
        title: 'Thư viện sản phẩm cho kinh doanh',
        type: 'item',
        permission: ['F120000'],
        url: '/kinh-doanh/san-pham-cho-kinh-doanh',
      },
      {
        id: 'sanphamchokinhdoanh',
        title: 'Danh sách so sánh thư viện sản phẩm với nguồn',
        type: 'item',
        permission: ['F120300'],
        url: '/kinh-doanh/so-sanh-thu-vien-san-pham-voi-nguon',
      },
      {
        id: 'quanlynhomkinhdoanh',
        title: 'Nhóm kinh doanh',
        type: 'item',
        permission: ['F120400'],
        url: '/kinh-doanh/nhom-kinh-doanh',
      },
      {
        id: 'quanlyungdung',
        title: 'Ứng dụng',
        type: 'item',
        permission: ['F120500'],
        url: '/kinh-doanh/ung-dung',
      },
      {
        id: 'dangkydoanhso',
        title: 'Đăng ký doanh số',
        type: 'item',
        // permission: ['F120500'],
        url: '/kinh-doanh/dang-ky-doanh-so',
      },
    ],
  },
  {
    id: 'import',
    title: 'NHẬP KHẨU',
    icon: 'directions_boat',
    type: 'collapsable',
    permission: ['F120600', 'F120650', 'F120660'],
    children: [
      {
        id: 'importPR',
        title: 'Import PR',
        type: 'item',
        permission: ['F120750'],
        url: '/nhap-khau/import-pr',
      },
      {
        id: 'hosonhapkhau',
        title: 'Hồ sơ nhập khẩu',
        type: 'item',
        permission: ['F120800'],
        url: '/nhap-khau/ho-so-nhap-khau',
      },
      {
        id: 'hosonhapkhau',
        title: 'Hồ sơ nhập khẩu đã kết thúc',
        type: 'item',
        permission: ['F120805'],
        url: '/nhap-khau/ho-so-nhap-khau-ket-thuc',
      },
      {
        id: 'cauhinhnhapkhau',
        title: 'Cấu hình tài liệu',
        type: 'item',
        permission: ['F120600'],
        url: '/nhap-khau/cau-hinh',
      },
      {
        id: 'reportdangthuchien',
        title: 'Báo cáo HS đang thực hiện',
        type: 'item',
        permission: ['F120650'],
        url: '/nhap-khau/report/dang-thuc-hien',
      },
      {
        id: 'reportonghop',
        title: 'Báo cáo HS đã kết thúc',
        type: 'item',
        permission: ['F120660'],
        url: '/nhap-khau/report/tong-hop',
      },
      {
        id: 'reporvandetondong',
        title: 'Báo cáo vấn đề tồn đọng',
        type: 'item',
        permission: ['F120850'],
        url: '/nhap-khau/report/van-de-ton-dong',
      },
    ],
  },
  {
    id: 'guideline',
    title: 'GUIDE LINE',
    icon: 'school',
    type: 'item',
    permission: [],
    url: '/huong-dan/guideline',
  },
  {
    id: 'category',
    title: 'DANH MỤC',
    icon: 'list',
    type: 'collapsable',
    permission: [],
    children: [
      // {
      //     id: 'categories',
      //     title: 'Quản lý danh mục',
      //     type: 'item',
      //     permission: [],
      //     url: '/danh-muc/quan-ly-danh-muc'
      // },
      {
        id: 'quoteStep',
        title: 'Các bước báo giá',
        type: 'item',
        permission: [],
        url: '/danh-muc/cac-buoc-bao-gia',
      },
      {
        id: 'technologySolution',
        title: 'Công nghệ cho giải pháp',
        type: 'item',
        permission: [],
        url: '/danh-muc/cong-nghe-cho-giai-phap',
      },
    ],
  },
];
