//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTS.Common.Resource.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng dụng.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM phòng thiết kế 2.
        /// </summary>
        public static string BOMDesignTwo {
            get {
                return ResourceManager.GetString("BOMDesignTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng viên.
        /// </summary>
        public static string Candidate {
            get {
                return ResourceManager.GetString("Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng tuyển.
        /// </summary>
        public static string CandidateApply {
            get {
                return ResourceManager.GetString("CandidateApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng cấp.
        /// </summary>
        public static string ClassIfication {
            get {
                return ResourceManager.GetString("ClassIfication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xếp loại.
        /// </summary>
        public static string Classifications {
            get {
                return ResourceManager.GetString("Classifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng học.
        /// </summary>
        public static string ClassRoom {
            get {
                return ResourceManager.GetString("ClassRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình File.
        /// </summary>
        public static string ConfigScanFile {
            get {
                return ResourceManager.GetString("ConfigScanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoá học.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người liên hệ.
        /// </summary>
        public static string CustomerContact {
            get {
                return ResourceManager.GetString("CustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại khách hàng.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thư mục.
        /// </summary>
        public static string DesignStructure {
            get {
                return ResourceManager.GetString("DesignStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File trong thư mục.
        /// </summary>
        public static string DesignStructureFile {
            get {
                return ResourceManager.GetString("DesignStructureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tài liệu.
        /// </summary>
        public static string DocumentGroup {
            get {
                return ResourceManager.GetString("DocumentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biên bản họp.
        /// </summary>
        public static string DocumentMeeting {
            get {
                return ResourceManager.GetString("DocumentMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vấn đề.
        /// </summary>
        public static string DocumentProblem {
            get {
                return ResourceManager.GetString("DocumentProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban hành.
        /// </summary>
        public static string DocumentPromulgate {
            get {
                return ResourceManager.GetString("DocumentPromulgate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài liệu.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình đào tạo.
        /// </summary>
        public static string EducationProgram {
            get {
                return ResourceManager.GetString("EducationProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu lực báo giá.
        /// </summary>
        public static string EffectiveLength {
            get {
                return ResourceManager.GetString("EffectiveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab khóa học.
        /// </summary>
        public static string EmployeeCourses {
            get {
                return ResourceManager.GetString("EmployeeCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng cấp.
        /// </summary>
        public static string EmployeeDegrees {
            get {
                return ResourceManager.GetString("EmployeeDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab giáo dục.
        /// </summary>
        public static string EmployeeEducations {
            get {
                return ResourceManager.GetString("EmployeeEducations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm nhân viên.
        /// </summary>
        public static string EmployeeGroup {
            get {
                return ResourceManager.GetString("EmployeeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab skill.
        /// </summary>
        public static string EmployeeSkillDetails {
            get {
                return ResourceManager.GetString("EmployeeSkillDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình đào tạo.
        /// </summary>
        public static string EmployeeTraining {
            get {
                return ResourceManager.GetString("EmployeeTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vấn đề/lỗi.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khắc phục lỗi/ vấn đề.
        /// </summary>
        public static string ErrorFix {
            get {
                return ResourceManager.GetString("ErrorFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm lỗi.
        /// </summary>
        public static string ErrorGroup {
            get {
                return ResourceManager.GetString("ErrorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên gia.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người thân.
        /// </summary>
        public static string Families {
            get {
                return ResourceManager.GetString("Families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File định nghĩa.
        /// </summary>
        public static string FileDefinition {
            get {
                return ResourceManager.GetString("FileDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng chảy.
        /// </summary>
        public static string FlowStage {
            get {
                return ResourceManager.GetString("FlowStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục định nghĩa.
        /// </summary>
        public static string FolderDefinition {
            get {
                return ResourceManager.GetString("FolderDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string FTP {
            get {
                return ResourceManager.GetString("FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tính năng.
        /// </summary>
        public static string FunctionGroups {
            get {
                return ResourceManager.GetString("FunctionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quyền.
        /// </summary>
        public static string GroupUser {
            get {
                return ResourceManager.GetString("GroupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ nhập khẩu.
        /// </summary>
        public static string ImportProfile {
            get {
                return ResourceManager.GetString("ImportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngành.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức đóng bảo hiểm.
        /// </summary>
        public static string InsuranceLevel {
            get {
                return ResourceManager.GetString("InsuranceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phỏng vấn.
        /// </summary>
        public static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm nghề.
        /// </summary>
        public static string JobGroup {
            get {
                return ResourceManager.GetString("JobGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý chức vụ.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng lao động.
        /// </summary>
        public static string LaborContract {
            get {
                return ResourceManager.GetString("LaborContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãng sản xuất.
        /// </summary>
        public static string Manufacture {
            get {
                return ResourceManager.GetString("Manufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hãng sản xuất.
        /// </summary>
        public static string ManufactureGroup {
            get {
                return ResourceManager.GetString("ManufactureGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật liệu điện, điện tử.
        /// </summary>
        public static string MaterialElectronic {
            get {
                return ResourceManager.GetString("MaterialElectronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm vật tư chức năng.
        /// </summary>
        public static string MaterialGroup {
            get {
                return ResourceManager.GetString("MaterialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm vật tư TPA.
        /// </summary>
        public static string MaterialGroupTPA {
            get {
                return ResourceManager.GetString("MaterialGroupTPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật liệu cơ khí.
        /// </summary>
        public static string MaterialMechanical {
            get {
                return ResourceManager.GetString("MaterialMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư chưa tồn tại.
        /// </summary>
        public static string MaterialNotDB {
            get {
                return ResourceManager.GetString("MaterialNotDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuộc họp.
        /// </summary>
        public static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủng loại cuộc họp.
        /// </summary>
        public static string MeetingType {
            get {
                return ResourceManager.GetString("MeetingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module nguồn.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm module nguồn.
        /// </summary>
        public static string ModuleGroup {
            get {
                return ResourceManager.GetString("ModuleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình thời gian công việc.
        /// </summary>
        public static string ModuleGroupTimeStandard {
            get {
                return ResourceManager.GetString("ModuleGroupTimeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả đầu ra.
        /// </summary>
        public static string OutputResult {
            get {
                return ResourceManager.GetString("OutputResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài thực hành.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm bài thực hành.
        /// </summary>
        public static string PracticeGroup {
            get {
                return ResourceManager.GetString("PracticeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn kĩ năng.
        /// </summary>
        public static string PracticeSkill {
            get {
                return ResourceManager.GetString("PracticeSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vấn đề.
        /// </summary>
        public static string ProblemExist {
            get {
                return ResourceManager.GetString("ProblemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm vấn đề.
        /// </summary>
        public static string ProblemExistGroup {
            get {
                return ResourceManager.GetString("ProblemExistGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sản phẩm.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm thiết bị.
        /// </summary>
        public static string ProductGroup {
            get {
                return ResourceManager.GetString("ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn sản phẩm.
        /// </summary>
        public static string ProductStandard {
            get {
                return ResourceManager.GetString("ProductStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tiêu chuẩn sản phẩm.
        /// </summary>
        public static string ProductStandardGroup {
            get {
                return ResourceManager.GetString("ProductStandardGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị nhập khẩu.
        /// </summary>
        public static string ProductStandardTPA {
            get {
                return ResourceManager.GetString("ProductStandardTPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủng loại hàng hóa.
        /// </summary>
        public static string ProductStandardTPAType {
            get {
                return ResourceManager.GetString("ProductStandardTPAType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp thiết kế.
        /// </summary>
        public static string ProjectGeneralDesign {
            get {
                return ResourceManager.GetString("ProjectGeneralDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giai đoạn dự án.
        /// </summary>
        public static string ProjectPhase {
            get {
                return ResourceManager.GetString("ProjectPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string ProjectProduct {
            get {
                return ResourceManager.GetString("ProjectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị dự án.
        /// </summary>
        public static string ProjectProducts {
            get {
                return ResourceManager.GetString("ProjectProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm câu hỏi.
        /// </summary>
        public static string QuestionGroup {
            get {
                return ResourceManager.GetString("QuestionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo giá.
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to công việc cho báo giá.
        /// </summary>
        public static string QuotationPlan {
            get {
                return ResourceManager.GetString("QuotationPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thiết bị.
        /// </summary>
        public static string QuotationProduct {
            get {
                return ResourceManager.GetString("QuotationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bước báo giá.
        /// </summary>
        public static string QuoteStep {
            get {
                return ResourceManager.GetString("QuoteStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật liệu.
        /// </summary>
        public static string RawMaterial {
            get {
                return ResourceManager.GetString("RawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do điều chỉnh thu nhập.
        /// </summary>
        public static string ReasonChangeIncome {
            get {
                return ResourceManager.GetString("ReasonChangeIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do thay đổi mức đóng BHXH.
        /// </summary>
        public static string ReasonChangeInsurance {
            get {
                return ResourceManager.GetString("ReasonChangeInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do nghỉ việc.
        /// </summary>
        public static string ReasonEndWorking {
            get {
                return ResourceManager.GetString("ReasonEndWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kênh tuyển dụng.
        /// </summary>
        public static string RecruitmentChannel {
            get {
                return ResourceManager.GetString("RecruitmentChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu tuyển dụng.
        /// </summary>
        public static string RecruitmentRequest {
            get {
                return ResourceManager.GetString("RecruitmentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo vấn đề tồn đọng.
        /// </summary>
        public static string ReportProblemExist {
            get {
                return ResourceManager.GetString("ReportProblemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trách nhiệm.
        /// </summary>
        public static string Responsibility {
            get {
                return ResourceManager.GetString("Responsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phòng học.
        /// </summary>
        public static string RoomType {
            get {
                return ResourceManager.GetString("RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm lương.
        /// </summary>
        public static string SalaryGroup {
            get {
                return ResourceManager.GetString("SalaryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức lương.
        /// </summary>
        public static string SalaryLevel {
            get {
                return ResourceManager.GetString("SalaryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngạch lương.
        /// </summary>
        public static string SalaryType {
            get {
                return ResourceManager.GetString("SalaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm kinh doanh.
        /// </summary>
        public static string SaleGroup {
            get {
                return ResourceManager.GetString("SaleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm kinh doanh.
        /// </summary>
        public static string SaleProducts {
            get {
                return ResourceManager.GetString("SaleProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất giữ.
        /// </summary>
        public static string SaleProductsExport {
            get {
                return ResourceManager.GetString("SaleProductsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủng loại hàng hóa.
        /// </summary>
        public static string SaleProductType {
            get {
                return ResourceManager.GetString("SaleProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch thiết kế .
        /// </summary>
        public static string ScheduleProject {
            get {
                return ResourceManager.GetString("ScheduleProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm vật tư tương tự.
        /// </summary>
        public static string SimilarMaterial {
            get {
                return ResourceManager.GetString("SimilarMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phác thảo thiết kế.
        /// </summary>
        public static string Sketches {
            get {
                return ResourceManager.GetString("Sketches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm kỹ năng.
        /// </summary>
        public static string SkillGroup {
            get {
                return ResourceManager.GetString("SkillGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỹ năng.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải pháp.
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm giải pháp.
        /// </summary>
        public static string SolutionGroup {
            get {
                return ResourceManager.GetString("SolutionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải pháp sản phẩm.
        /// </summary>
        public static string SolutionProduct {
            get {
                return ResourceManager.GetString("SolutionProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên môn.
        /// </summary>
        public static string Specialize {
            get {
                return ResourceManager.GetString("Specialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công đoạn.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn học.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm nhà cung cấp.
        /// </summary>
        public static string SupplierGroup {
            get {
                return ResourceManager.GetString("SupplierGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc theo nhóm module.
        /// </summary>
        public static string TaskModuleGroup {
            get {
                return ResourceManager.GetString("TaskModuleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cho công việc.
        /// </summary>
        public static string TaskTimeStandard {
            get {
                return ResourceManager.GetString("TaskTimeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mã số thuế.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ cho giải pháp.
        /// </summary>
        public static string TechnologySolution {
            get {
                return ResourceManager.GetString("TechnologySolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chí kiểm tra.
        /// </summary>
        public static string TestCriteria {
            get {
                return ResourceManager.GetString("TestCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tiêu chí kiểm tra.
        /// </summary>
        public static string TestCriteriaGroup {
            get {
                return ResourceManager.GetString("TestCriteriaGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật kí công việc.
        /// </summary>
        public static string WorkDiary {
            get {
                return ResourceManager.GetString("WorkDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi làm việc.
        /// </summary>
        public static string WorkLocation {
            get {
                return ResourceManager.GetString("WorkLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị công tác.
        /// </summary>
        public static string WorkPlace {
            get {
                return ResourceManager.GetString("WorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỹ năng.
        /// </summary>
        public static string WorkSkill {
            get {
                return ResourceManager.GetString("WorkSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm kỹ năng.
        /// </summary>
        public static string WorkSkillGroup {
            get {
                return ResourceManager.GetString("WorkSkillGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm việc.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí công việc.
        /// </summary>
        public static string WorkType {
            get {
                return ResourceManager.GetString("WorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phỏng vấn vị trí công việc.
        /// </summary>
        public static string WorkTypeInterview {
            get {
                return ResourceManager.GetString("WorkTypeInterview", resourceCulture);
            }
        }
    }
}
