//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagementSystem.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPA_Message
    {
        public int Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Type { get; set; }
        public string Content { get; set; }
    }
}
